### ISSUE TITLE
Refactor DB

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/BORROW-APP#29]
> DB being refactor to reflect different relevant cases for demo

---
- [x] Recfactor DB
- [x] Register required cases with standard secret string
- [x] Run Unit tests to ensure functionality

**Comment by Medic1111** [comment]
@cappreccia-swanson This Task has been completed. =)  You may close it at your will
Thank you

**Comment by cappreccia-swanson** [comment]
10-4
